### ISSUE TITLE
various spelling mistakes & 3 cmd examples are incorrect

### ISSUE THREAD

**Issue by bmullan** [sferket/LXD-Infrastructure-Manager#3]
small fyi but there are various spelling mistakes
and I believe there are several command examples that are not correct as I think you meant each to be separated on multiple lines ?:

1st cmd:

**lxc launch ubuntu:16.04 sandbox-16 Get shell: lxc exec sandbox-16 -- /bin/bash**

lxc launch ubuntu:16.04 sandbox-16

Get shell:
lxc exec sandbox-16 --/bin/bash

2nd cmd:

**adduser lxd_panel adduser lxd_panel lxd**

adduser lxd_panel
...

then 
adduser lxd_panel lxd

3rd cmd:
same goes for the command example:

**Add certificatee to trust: lxc config trust list lxc config trust add /root/.config/lxc/client.crt lxc config trust list**

lxc config trust list
lxc config trust add /root/.config/lxc/client.crt

then to verify it got set..
lxc config trust list

also... just for clarity you might want to indicate use of sudo 

thanks..!
brian

**Comment by sferket** [comment]
Thank you for your contribution. We updated the README to make it better readable.
