### ISSUE TITLE
the ReadMe doesn't really say "what" is used to or how manage the multiple servers

### ISSUE THREAD

**Issue by bmullan** [sferket/LXD-Infrastructure-Manager#4]
Maybe I missed something but since the instructions say to add a lxd_panel user...  is this whole thing intended to be used with something like lxd-webgui or some other tool ?

In other words "how" does someone use this?

Sorry but the ReadMe doesn't really describe what to do to get started after the installation

**Comment by sferket** [comment]
Thank you for your contribution. We updated the README and added a screenshot.
